### ISSUE TITLE
Extend Pytorch

### ISSUE THREAD

**Issue by PowerChell** [fiboa/software#4]
Release Pytorch extension for working with Fiboa + AI extension, and ideally fully working with ASU dataset, with examples.

**Comment by m-mohr** [comment]
Should this be in the extensions repo? Or what is meant by extension here in software?

**Comment by PowerChell** [comment]
@m-mohr Yeah, I think you're right!

**Comment by suredream** [comment]
hi @PowerChell interested with it as well and curious how to contribute.  Can you see more details and any basic tests in your mind?

**Comment by PowerChell** [comment]
hi @suredream 👋 If you are able, please join our [bi-weekly meeting](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MnQ3cXJmdjM4bjJibGN1cjQzZjRmanZmdTZfMjAyNDA0MTdUMTUwMDAwWiBjX2U0NmNkMTRlMmU1OWQxOWMzMTNjMDIwYjI5ZmVlYmFhN2Y2MGQzYzc4OTdjNjNlZWQ5ODgyZjQwOGFiYjQxZWVAZw&tmsrc=c_e46cd14e2e59d19c313c020b29feebaa7f60d3c7897c63eed9882f408abb41ee%40group.calendar.google.com&scp=ALL) tomorrow at 11 EST. There, we can discuss more in depth. If you are unable to join, I can share more information here on this thread after the meeting.

**Comment by suredream** [comment]
I can be there. However, a brief desc of the goal/scope in issue will be google enough..

**Comment by suredream** [comment]
hi @cholmes @PowerChell I attended today's meeting and got some context info from the Aninda Ghosh. I understand right now the effort is on the boundaries data collection and benchmark experiments. Once we can benchmark datasets from different sources and feel safe to compile them,  **a torch data loader** or **adapter** will be needed to move the datasets for operation in [TorchGeo loaders](https://torchgeo.readthedocs.io/en/stable/api/datasets.html#non-geospatial-datasets)

Please do clarification and specify the requirements @cholmes. I would like to know other members' skill so get better idea that when/how we can achieve them. Would break down more tickets if needed. Many thanks,

**Comment by m-mohr** [comment]
I think this is done.
